"""first migration

Revision ID: 2c689e9e3b6c
Revises: 
Create Date: 2025-04-03 02:57:18.905158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c689e9e3b6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_usage', schema=None) as batch_op:
        batch_op.drop_column('acknowledged')

    # ### end Alembic commands ###
